### ISSUE TITLE
Do you need any help here?

### ISSUE THREAD

**Issue by tiagodavi** [DockYard/rein#2]
@polvalente Are you planning to add a backlog or something here to be done? 

Please let me know if you need any help, I would like to contribute to this library as well. 

Thanks.

**Comment by polvalente** [comment]
Awesome, thanks for asking! I'll add some issues that can serve as a starting point!

**Comment by polvalente** [comment]
@tiagodavi Sorry this took so long. I ran into a few bugs and took the time to fix them before opening the issues.
I've opened some issues with varying levels of difficulty. I'm closing this one, but if you want to tackle any of those, just let me know!
